### PR TITLE
Move event history to a separate tab

### LINKED ISSUE #22: Move event history to third tab
- Current State
- Total State
- History

### PR DESCRIPTION
**Pull request by beevee**
Closes #22

### CODE REVIEW

**Comment by gmlexx** [comment]
Looks good, I added a little fix. Merge if you liked it.

**Comment by beevee** [comment]
If we add hover highlighting here, we should add it everywhere. For example, on "simple mode" - "advanced mode" tabs.

**Comment by beevee** [comment]
Also, materializecss has different tabs highlighting, see here: http://materializecss.com/tabs.html

I propose we remove highlighting from this unrelated PR and fix it for all tabs in a different branch.

**Comment by beevee** [comment]
#30

**Pull request merged**
