### PR TITLE
Enhancement of formatting of long targets

### PR DESCRIPTION
**Pull request by melnikk**
1. Added angular-sanitize dependency for ng-bind-html directive
2. Added filter module indent.ts
3. For binding indentation use: {{ expression | indent }}

@beevee for review

### CODE REVIEW

**Comment by gmlexx** [comment]
Please, squash commits before merge

**Comment by melnikk** [comment]
@gmlexx package.json raises conflict. Could you fix it when merge?

**Comment by gmlexx** [comment]
Use the same indentation as in master branch. That woun't be such a mess conflict.
The only things, that has changed is addition of "angular-sanitize": "1.4.7",

**Comment by melnikk** [comment]
@gmlexx still conflicts. Will fix when write a [test](https://github.com/moira-alert/web/issues/31#issuecomment-232605474).

**Comment by gmlexx** [comment]
Sorry, I was wrong.
Conflict is caused by upgrading deps in package.json.
1. So my suggestion is to stash your changes without package.json
2. Pull latest master branch
3. Rollup your changes from stash
4. Add "angular-sanitize": "1.4.7" to deps in package.json again.

**Comment by melnikk** [comment]
@gmlexx fixed

**Comment by gmlexx** [comment]
Good job, thanx

**Pull request merged**
