### PR TITLE
Proper order of events on "EVENT HISTORY"

### PR DESCRIPTION
**Pull request by tantra35**
Moira make inproper events order when show them

### CODE REVIEW

**Comment by gmlexx** [comment]
Thanks for PR.
I've checked out it, and do not understand, what are you expecting from it.

Existing order is current design decision.
There are several cases of events history usage.
1. Different metrics are independent from each other.
   So you need to group events by metric name.
   This is how it shows now. Groups list is not sorted. But inside group, events are sorted by time descending.
2. No sense in grouping events by metrics. List of all events by descending order.

There may be some switch between this cases in UI.

P.S. current behaviour may be improved by sorting of events groups

**Comment by gmlexx** [comment]
This is how list order looks now from your PR.

**Comment by gmlexx** [comment]
BTW.
In typescript this constriction is redundant.

constructor(public _metric: string) {
        this.metric = _metric;
}

You will have two fields: _metric and metric

This is enough
constructor(public metric: string) {
}

**Comment by tantra35** [comment]
It is very strange that the chronology is lost. I expect that Today will by at top

moira-wrong-history-order

Without patch "Today" printed at the middle of page, not at the top. At the top we see 12 january. With patch picture different: "Today" with current trigger expression on the top of page in in the right chronological order

moira-wrong-history-order-fix

I brought a clipping from the screen(when patch applied) so that it is clear that over time, changed the trigger expression

**Comment by tantra35** [comment]
Also look at expression field, it partialy hidden, and doesn't shown fully. But this is another bug

**Comment by gmlexx** [comment]
Fix order in v1.0.1

**Comment by beevee** [comment]
As of current master, metrics on this page should appear chronologically sorted. Fixed here: https://github.com/moira-alert/web/commit/376699f7a007830673399d6806c0d8ccd9eb16e2

**Pull request closed without merging**
