### PR TITLE
Make navbar mobile-friendly

### PR DESCRIPTION
**Pull request by beevee**
SEE #20 

You can review this commit-by-commit.

First commit plugs in materializecss via SASS loaders, which is the official way to customize variables, like colors.

Last commit is a step towards more idiomatic usage of materializecss. Changes included:
- Navbar is adaptive now, which was obviously the entire reason of making this PR.
- "Add" action buttons on main page and settings page are consistent with material design guidelines (large red circle in the bottom-right corner).
- "Settings" and "Help" buttons are now more consistent with material design guidelines, too. They are still buttons on the navbar, though.

@gmlexx @AlexAkulov let me know what you think

### CODE REVIEW

**Comment by beevee** [comment]
Looks like this for now. I didn't touch the page contents, only navbar yet.

**Comment by beevee** [comment]
Desktop version.

**Comment by gmlexx** [comment]
It is a bit hard to find "Add button" on desktop, but ok, let's be more mobile :)

**Comment by beevee** [comment]
I hope that people familiar with Google services (e.g. Inbox) will find it :)

**Pull request merged**
