### PR TITLE
Feature target search with list

### PR DESCRIPTION
**Pull request by aversant**
Add search to target field on 'Create trigger' page. When you type target's name do request 'GET /api/targets?search=<typed text>' and drop down list display match target's name.

example_search_screenshot

### CODE REVIEW

**Comment by beevee** [comment]
Thanks for the PR!

But do you know that Moira stores only metrics that match one of the existing triggers? So, if you are creating a new trigger, Moira probably won't be able to suggest you anything?

**Comment by gmlexx** [comment]
Yes, the main problem that moira doesn't know possible metrics before trigger was saved and cache began saving those metrics.
May be we can resolve this problem in cache firstly and save all metrics names somewhere, even if metrics filtered and its values don't saved.

**Comment by beevee** [comment]
Maybe we can try a Redis SET for metric names?

**Comment by gmlexx** [comment]
Yeah, seems ok.
https://github.com/moira-alert/cache/issues/5

**Comment by aversant** [comment]
I have planned add to moira/cache functional of add metric name to redis hash 'moira-all-targets' 
{'target_name': '', ttl: '1000'}.
ttl for stored time and clear metric if they no data (or other reason) a lot of time.

**Comment by AlexAkulov** [comment]
Why do you need to do it? Everyone creates targets in Grafana and copy to Moira. 
If we want to change this usecase we need to show not only the metrics names but also the functions and to draw graphics.

**Comment by aversant** [comment]
In my case (metrics collected on network devices), the targets are generated dynamically. And if I want create alerts first time (after install moira-alerts) copy-paste is more take time.
But, I agree - if initial configuration complete the targets searching not the primary feature.
Perhaps, it is only my usecase need to it. This is the first one I had when setting moira-alert. And I thought - that it is necessary.

**Pull request closed without merging**
