### PR TITLE
Make triggers page mobile-friendly

### PR DESCRIPTION
**Pull request by beevee**
Big changes, so look carefully.
1. Switched to 24-column grid to be more flexible. Most of the changes in files are related to this: I had to multiply all column sizes 2x.
2. Started to migrate CSS and inline styles to SASS, so we can use variables and inheritance from materializecss. Eventually, we will move all classes to SASS and delete moira.css.
3. Started to unify colors, margins and other stuff with materializecss defaults. We should use more named colors from their palette instead of defining them inline with #hex.
4. Migrated from table to grid on triggers page. This is the only reasonable way to introduce adaptive layout.
5. Changed order of state columns to reverse (OK, WARN, ERROR, NODATA) and aligned it to the right side. This way we will use horizontal space more efficiently and avoid big gaps. Also, moved last event time to the left side of states.
6. Removed gray background on hover. I think, we should eventually migrate to more idiomatic materialize style with shadows and depth instead of background.

Let me know if something is broken, especially on large desktop resolutions.

### CODE REVIEW

**Comment by beevee** [comment]
Please, help with tests, if you can :)

**Comment by gmlexx** [comment]
You should not have been removed trigger-row class from markup.
It's used by failed test.
If there is more elegant way to check number of trigger rows in markup - welcome.

**Comment by gmlexx** [comment]
A bit different background color on logo, than header back-ground color.

**Pull request merged**
